import icaro.infraestructura.recursosOrganizacion.recursoTrazas.ItfUsoRecursoTrazas;
import icaro.infraestructura.recursosOrganizacion.recursoTrazas.imp.componentes.InfoTraza;
import icaro.aplicaciones.recursos.persistenciaMensajesGrupo.*;
import icaro.infraestructura.entidadesBasicas.procesadorCognitivo.*;
import icaro.infraestructura.patronAgenteCognitivo.procesadorObjetivos.gestorTareas.ItfGestorTareas;
import icaro.infraestructura.entidadesBasicas.PerformativaUsuario;
import icaro.infraestructura.entidadesBasicas.NombresPredefinidos;
import icaro.infraestructura.entidadesBasicas.comunicacion.*;
import icaro.aplicaciones.agentes.AgenteAplicacionGestionQuedadas.objetivos.*;
import icaro.aplicaciones.agentes.AgenteAplicacionGestionQuedadas.tareas.*;
import icaro.aplicaciones.agentes.AgenteAplicacionGestionQuedadas.tools.*;
import icaro.aplicaciones.informacion.gestionQuedadas.*;

global ItfGestorTareas gestorTareas;
global ItfUsoRecursoTrazas recursoTrazas;
global String agentId;


rule "Recibir grupo identificado"
 when
 	notif:NotificacionIdentificado(chat:identNotificador, gr:grupo)
 then
 	Objetivo ob = new ObtenerNuevosMensajesGrupo();
 	ob.setobjectReferenceId(chat);
 	FocoGrupo fc = new FocoGrupo(chat);
 	insert(fc);
 	insert(gr);
    insert(ob);
    retract(notif);
 	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId,"EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Obtener nuevos mensajes desde persistencia"
 when
 	ob:ObtenerNuevosMensajesGrupo(chat:objectReferenceId, state == Objetivo.PENDING)
 	gr:Grupo(grupo == chat)
 then
 	ItfPersistenciaMensajesGrupo persistencia = (ItfPersistenciaMensajesGrupo) NombresPredefinidos.REPOSITORIO_INTERFACES_OBJ.obtenerInterfazUso(VocabularioGestionQuedadas.IdentRecursoPersistenciaMensajesGrupo);
	MensajeGrupo mgr = persistencia.obtenerMensajeGrupo(gr.getId());
	if (mgr != null) {
		insert(mgr);
		persistencia.eliminarMensajeGrupo(gr.getId());		
	}
end
