import icaro.infraestructura.recursosOrganizacion.recursoTrazas.ItfUsoRecursoTrazas;
import icaro.infraestructura.recursosOrganizacion.recursoTrazas.imp.componentes.InfoTraza;
import icaro.infraestructura.entidadesBasicas.procesadorCognitivo.*;
import icaro.infraestructura.patronAgenteCognitivo.procesadorObjetivos.gestorTareas.ItfGestorTareas;
import icaro.infraestructura.entidadesBasicas.PerformativaUsuario;
import icaro.infraestructura.entidadesBasicas.comunicacion.*
import icaro.aplicaciones.agentes.AgenteAplicacionIdentificador.objetivos.*;

import icaro.aplicaciones.informacion.gestionCitas.*; 

import icaro.aplicaciones.informacion.gestionQuedadas.*;
import icaro.aplicaciones.agentes.AgenteAplicacionIdentificador.tareas.*;
import icaro.aplicaciones.agentes.AgenteAplicacionIdentificador.tools.*;
import icaro.aplicaciones.agentes.AgenteAplicacionDialogoPaciente.tools.*;
import icaro.aplicaciones.agentes.AgenteAplicacionDialogoMedico.tools.*;
import static icaro.aplicaciones.recursos.persistenciaUsuarios.imp.PersistenciaUsuariosImp.*;

global ItfGestorTareas gestorTareas;
global ItfUsoRecursoTrazas recursoTrazas;
global String agentId;


rule "Creacion de los objectivos iniciales"
when 
then 
TareaSincrona tarea = gestorTareas.crearTareaSincrona(InicializarInfoWorkMem.class);
    tarea.ejecutar();
recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
end

rule "Saludo Inicial"
when
then
   // recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Se ejecuta la tarea : SolicitarDatosAcceso",InfoTraza.NivelTraza.debug));
     TareaSincrona tarea = gestorTareas.crearTareaSincrona(SaludoInicial.class);
     tarea.ejecutar(VocabularioGestionQuedadas.IdentRecursoComunicacionChat);
   // recursoTrazas.aceptaNuevaTraza(new InfoTraza(agentId,"Realizando el objetivo : "+obj.getgoalId()+"  Ejecutando la tarea : "+ tarea.getIdentTarea() ,InfoTraza.NivelTraza.debug));
   // recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Saludo inicial al grupo"
 when
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion == tipoNotif.saludo)
    not( exists (Grupo(grupo == identInterlc )))
 then
 	Grupo gr = new Grupo();
 	gr.grupo = identInterlc;
 	insert( gr );
 	FocoGrupo fgr = new FocoGrupo(identInterlc);
 	Objetivo id = new IdentificarGrupo();
 	id.setobjectReferenceId(identInterlc);
 	insert( fgr );
 	insert( id );
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
    tarea.ejecutar(identInterlc,conversacion.msg("saludoInicial"));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
    retract(notif);
end


rule "Saludo inicial descortes"
 when
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion != tipoNotif.saludo)
    not( exists (Grupo(grupo == identInterlc )))
 then
 	Grupo gr = new Grupo();
 	gr.grupo = identInterlc;
 	insert( gr );
 	FocoGrupo fgr = new FocoGrupo(identInterlc);
 	Objetivo id = new IdentificarGrupo();
 	id.setobjectReferenceId(identInterlc);
 	insert( fgr );
 	insert( id );
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
    tarea.ejecutar(identInterlc,conversacion.msg("saludoInicialDescortes"));
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
    retract(notif);
end


rule "Resaludar"
 when
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion == tipoNotif.saludo)
   	gr:Grupo(grupo == identInterlc)
 then
  	 TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
     tarea.ejecutar(identInterlc,conversacion.msg("resaludar"));
     recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName()); 
     gr.actividad();
     retract(notif);
end

/*rule "Regla de solicitar edad del grupo"
 when
 	
 	fc:FocoGrupo(fcgroup:grupo , foco == null)
 	obj:IdentificarGrupo(state == Objetivo.PENDING ,objectReferenceId == fcgroup )
 	not( exists (ObtenerEdad(objectReferenceId == fcgroup)))
 then
  	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
  	Objetivo no = new ObtenerEdad();
  	no.setobjectReferenceId(fcgroup);
  	fc.setFoco(no);
  	
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
    tarea.ejecutar(fcgroup,conversacion.msg("solicitarEdad"));
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	update(fc);
   	insert(no);
end

rule "Regla de obtencion de la edad del grupo"
 when
	obj:ObtenerEdad(group:objectReferenceId, state == Objetivo.PENDING)
 	fc:FocoGrupo(grupo == group, foco == obj )
    notif:Notificacion(identNotificador == group, tipoNotificacion == tipoNotif.nombre, msgg:mensajeNotificacion )
    // notif:Notificacion(identNotificador == user, msgg:mensajeNotificacion )
    gr:Grupo(grupo == group)
 then
 	obj.setSolved();
 	gr.setEdad(msgg);
 	gr.actividad();
 	fc.setFoco(null);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(SolicitarEdad.class);
    tarea.ejecutar(group,conversacion.msg("solicitarEdad"),msgg);
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	
   	update(obj);
   	update(fc);
   	retract(notif);
end
*/

rule "Regla de solicitud del identificador del grupo"
 when
 	fc:FocoGrupo(fcgroup:grupo , foco == null)
 	obj:IdentificarGrupo(state == Objetivo.PENDING ,objectReferenceId == fcgroup )
 	not( exists (ObtenerIDGrupo(objectReferenceId == fcgroup)))
 then

  	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
  	Objetivo ob = new ObtenerIDGrupo();	
	ob.setobjectReferenceId(fcgroup);
	insert(ob);
	fc.setFoco(ob);
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
  	tarea.ejecutar(fcgroup, conversacion.msg("peticionIDGrupo"));	
  
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
    update(obj);
    update(fc);
end

rule "Regla de obtencion del identificador del grupo"
 when
 	obj:ObtenerIDGrupo(group:objectReferenceId, state == Objetivo.PENDING)
 	fc:FocoGrupo(grupo == group, foco == obj )
    notif:Notificacion(identNotificador == group, tipoNotificacion == tipoNotif.idgrupo, msgg:mensajeNotificacion )
    gr:Grupo(grupo == group)
 then
 	obj.setSolved();
 	gr.setId(msgg);
 	gr.actividad();
 	fc.setFoco(null);
    TareaSincrona tarea = gestorTareas.crearTareaSincrona(ObtenerGrupoDesdePersistencia.class);
    tarea.ejecutar(group,gr);
   	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   	
   	update(obj);
   	update(fc);
   	retract(notif);
end

rule "Notificar desconocimiento"
 when
 	notif:Notificacion(group:identNotificador, tipoNotificacion == VocabularioGestionQuedadas.ExtraccionSemanticaNull )
 	fc:FocoGrupo(grupo == group)
 	gr:Grupo(grupo == group);
 then
 	TareaSincrona tarea = gestorTareas.crearTareaSincrona(NotificarAlGrupoSinContexto.class);
    tarea.ejecutar(fc);
    gr.actividad();
    retract(notif);
    update(fc);
    update(gr);
 	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Finalizar la identificacion"
 when
 	ObtenerIDGrupo(user:objectReferenceId, state == Objetivo.SOLVED);
 	ObtenerNombre(objectReferenceId == user, state == Objetivo.SOLVED)
 	obj:IdentificarUsuario(state == Objetivo.PENDING ,objectReferenceId == user )
 	cu:UsuarioContexto(usuario == user)
 	fc:FocoUsuario(usuario == user)
 then
 	TareaSincrona tarea = gestorTareas.crearTareaSincrona(UsuarioIdentificado.class);
 	tarea.ejecutar(user, cu);
 	fc.setFoco(null);
 	//TODO GUARDAR EN LA PERSISTENCIA USUARIO PARA PODER USARLA LUEGO 
 	Tarea tarea2 = gestorTareas.crearTarea(NotificarUsuarioIdentificado.class);
    tarea2.ejecutar(cu);
    insertarUsuario(user,cu);

	NotificacionObjetivo f = new NotificacionObjetivo();
	f.setTipoNotificacion(tipoNotif.objetivo);
	f.setAgente("INIT");
	f.identNotificador = user;
	insert(f);

 	obj.setSolved();
 	update(obj);
 	update(fc);
end

rule "Contexto incorrecto Luego de identificar"
 when 
   notif:Notificacion(identInterlc:identNotificador, 
    		tipoNotificacion != tipoNotifPaciente.inicioPeticion &&
    		tipoNotificacion != tipoNotifPaciente.consulta && 
    		tipoNotificacion != tipoNotif.saludo && tipoNotificacion != tipoNotif.despedida)
    //obj:DistribuirMensajes(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
    fc:FocoUsuario(usuario == identInterlc, foco == null)
    cu:UsuarioContexto(usuario == identInterlc)
 then
  	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
  	tarea.ejecutar(identInterlc, cu.getNombre()+ ", " + conversacion.msg("distribucion"));	
  	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
  	retract(notif);
end

rule "Recibir Objetivo primera vez"
 when 
 	notif:NotificacionObjetivo(identInterlc:identNotificador, tipoNotificacion == tipoNotif.objetivo, agente == "INIT")
 	//obj:DistribuirMensajes(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
 	obj:IdentificarUsuario(state == Objetivo.SOLVED ,objectReferenceId == identInterlc )
    fc:FocoUsuario(usuario == identInterlc, foco == null)
    cu:UsuarioContexto(usuario == identInterlc)
 then
 	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
  	tarea.ejecutar(identInterlc, cu.getNombre()+ ", " + conversacion.msg("distribucion"));	
 	cu.actividad();
	fc.refocus();
	update(fc);
	update(cu);
 	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
 	retract(notif);
end
/*
rule "Focalizacion de distribucion de mensajes"
 when
    obj:IdentificarUsuario(state == Objetivo.SOLVED ,user:objectReferenceId)
    cu:UsuarioContexto(usuario == user)
    fc:FocoUsuario(usuario == user)
 then
	obj.setSolving();
	Objetivo dm = new DistribuirMensajes();
	dm.setobjectReferenceId(user);
	fc.setFoco(dm);
	dm.setSolving();

  TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
     tarea.ejecutar(user, cu.getNombre()+ ", " + conversacion.msg("distribucion"));
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   update(obj);
   	insert(dm);
	update(fc);
end
*/

rule "Solicita Distribucion de mensajes paciente"
 when
    notif:Notificacion(identInterlc:identNotificador, 
    		(tipoNotificacion == tipoNotifPaciente.inicioPeticion ||
    		tipoNotificacion == tipoNotifPaciente.consulta) && 
    		tipoNotificacion != tipoNotif.saludo && tipoNotificacion != tipoNotif.despedida)
    //obj:DistribuirMensajes(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
    fc:FocoUsuario(usuario == identInterlc)
    cu:UsuarioContexto(usuario == identInterlc)
 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
	cu.actividad();
    Tarea tarea = gestorTareas.crearTarea(Distribuir.class);
    tarea.ejecutar(identInterlc, notif, VocabularioGestionQuedadas.IdentAgenteAplicacionDialogoPaciente);
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
    retract(notif);
end

rule "Distribucion de mensajes paciente"
 when
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion != tipoNotif.saludo && tipoNotificacion != tipoNotif.despedida)
    obj:DistribuirMensajesPaciente(state == Objetivo.PENDING, objectReferenceId == identInterlc)
    fc:FocoUsuario(usuario == identInterlc, foco == obj)
    cu:UsuarioContexto(usuario == identInterlc)
 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
	cu.actividad();
  	Tarea tarea = gestorTareas.crearTarea(Distribuir.class);
    tarea.ejecutar(identInterlc, notif, VocabularioGestionQuedadas.IdentAgenteAplicacionDialogoPaciente);
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   retract(notif);
end

rule "Recibir Objetivo Paciente"
 when 
 	notif:NotificacionObjetivo(identInterlc:identNotificador, agente == "PACIENTE")
 	//obj:DistribuirMensajes(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
    fc:FocoUsuario(usuario == identInterlc)
    cu:UsuarioContexto(usuario == identInterlc)
 then
	Objetivo dp = new DistribuirMensajesPaciente();	
	dp.setobjectReferenceId(identInterlc);
	cu.actividad();
	fc.setFoco(dp);
	insert(dp);
	update(fc);
	update(cu);
 	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
 	retract(notif);
end


rule "Solicita Distribucion de mensajes medico"
 when
    notif:Notificacion(identInterlc:identNotificador, 
    		tipoNotificacion == tipoNotifMedico.inicioAnulacion && 
    		tipoNotificacion != tipoNotif.saludo && tipoNotificacion != tipoNotif.despedida)
    //obj:DistribuirMensajes(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
    fc:FocoUsuario(usuario == identInterlc)
    cu:UsuarioContexto(usuario == identInterlc)
 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
	cu.actividad();
    Tarea tarea = gestorTareas.crearTarea(Distribuir.class);
    tarea.ejecutar(identInterlc, notif, VocabularioGestionQuedadas.IdentAgenteAplicacionDialogoMedico);
    recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
    retract(notif);
end

rule "Distribucion de mensajes medico"
 when
    notif:Notificacion(identInterlc:identNotificador, tipoNotificacion != tipoNotif.saludo && tipoNotificacion != tipoNotif.despedida)
    obj:DistribuirMensajesMedico(state == Objetivo.PENDING, objectReferenceId == identInterlc)
    fc:FocoUsuario(usuario == identInterlc, foco == obj)
    cu:UsuarioContexto(usuario == identInterlc)
 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
	cu.actividad();
  	Tarea tarea = gestorTareas.crearTarea(Distribuir.class);
    tarea.ejecutar(identInterlc, notif, VocabularioGestionQuedadas.IdentAgenteAplicacionDialogoMedico);
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   retract(notif);
end

rule "Recibir Objetivo Medico"
 when 
 	notif:NotificacionObjetivo(identInterlc:identNotificador, agente == "MEDICO")
 	//obj:DistribuirMensajes(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
    fc:FocoUsuario(usuario == identInterlc)
    cu:UsuarioContexto(usuario == identInterlc)
 then
	Objetivo dp = new DistribuirMensajesMedico();	
	dp.setobjectReferenceId(identInterlc);
	cu.actividad();
	fc.setFoco(dp);
	insert(dp);
	update(fc);
	update(cu);
 	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
 	retract(notif);
end

rule "Recibir Objetivo Completado"
 when 
 	notif:NotificacionObjetivo(identInterlc:identNotificador, tipoNotificacion == tipoNotif.objetivo, agente == "RESET")
 	//obj:DistribuirMensajes(state == Objetivo.SOLVING, objectReferenceId == identInterlc)
    fc:FocoUsuario(usuario == identInterlc, foco != null)
    cu:UsuarioContexto(usuario == identInterlc)
 then
 	TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
  	tarea.ejecutar(identInterlc, conversacion.msg("objetivoLogrado"));	
 	cu.actividad();
	fc.refocus();
	update(fc);
	update(cu);
 	recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
 	retract(notif);
end



rule "Detectar Inactividad"
	when 
	 cu:UsuarioContexto(user:usuario, inactividad(1) );
	 not( exists Inactividad(user == objectReferenceId ))
	 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
	Objetivo obb = new Inactividad();
	obb.setobjectReferenceId(user);
	insert( obb );
	cu.actividad();
  TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
  	if( cu.getNombre() == null){
  		tarea.ejecutar(cu.getUsuario(), conversacion.msg("inactividad"));
  	}else{
  		tarea.ejecutar(cu.getUsuario(), cu.getNombre() +", "+ conversacion.msg("inactividad"));
  	}
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
end

rule "Detectar Inactividad prolongada"
	when 
 	 cu:UsuarioContexto(user:usuario, inactividad(2) );
	 Inactividad(user == objectReferenceId, state == Objetivo.PENDING );
	 
	 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
  TareaSincrona tarea2 = gestorTareas.crearTareaSincrona(EliminarSessionUsuario.class);
     tarea2.ejecutar(cu.usuario);
  TareaSincrona tarea = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
     tarea.ejecutar(user,  conversacion.msg("despedida"));
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   retract( cu );
end

rule "Despedirse"
	when 
	 notif:Notificacion(identInterlc:identNotificador, tipoNotificacion == tipoNotif.despedida)
 	 gr:Grupo(grupo == identInterlc );
	 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
   Tarea tarea = gestorTareas.crearTarea(EliminarSesionGrupo.class);
     tarea.ejecutar(gr.grupo);
   TareaSincrona tarea2 = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
     tarea2.ejecutar(gr.grupo,  conversacion.msg("despedida"));
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   retract( gr );
   retract( notif );
end

rule "fechaAnterior"
	when 
	 notif:Notificacion(identInterlc:identNotificador, tipoNotificacion == tipoNotif.fechaAnterior)
	 cu:UsuarioContexto(usuario == identInterlc );
	 then
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTARA LA REGLA: " + drools.getRule().getName());
   TareaSincrona tarea2 = gestorTareas.crearTareaSincrona(MensajeGenerico.class);
     tarea2.ejecutar(cu.usuario,  conversacion.msg("fechaAnterior"));
   recursoTrazas.aceptaNuevaTrazaEjecReglas(agentId," EJECUTO LA REGLA: " + drools.getRule().getName());
   retract( notif );
end


	
	
rule "Timer Inactividad"
	timer ( int: 1m )
	when 
	 m:UsuarioContexto()
	 then
   update(m);
end
	

